services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_server
    networks:
      - analytics_network
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse_data:/var/lib/clickhouse
    env_file:
      - .env

volumes:
  clickhouse_data:

networks:
  analytics_network:
    external: true