name: Test

on:
  workflow_dispatch:

jobs:
  test_job:
    services:
      clickhouse-server:
        image: clickhouse/clickhouse-server:latest
        ports:
          - "8123:8123"
          - "9000:9000"
        volumes:
          - clickhouse_data:/var/lib/clickhouse
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: test
      shell: bash
      run: docker ps && echo 1
    - name: run client
      shell: bash
      run: |
        NAME=$(sudo docker ps --format json | jq 'select(.Image=="clickhouse/clickhouse-server:latest")' | jq -r .Names) 
        echo $NAME
        pip install clickhouse-connect
        python3 clickhouse_test.py
        
