name: Test

on:
  workflow_dispatch:

jobs:
  test_job:
    services:
      clickhouse-server:
        image: clickhouse/clickhouse-server:latest
        env:
          CLICKHOUSE_USER: ${{ secrets.CLICKHOUSE_USER }}
          CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
        ports:
          - "8123:8123"
          - "9000:9000"
        volumes:
          - clickhouse_data:/var/lib/clickhouse
    runs-on: ubuntu-22.04
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Download python requirements
      shell: bash
      run: pip install -r requirements.txt
    
    - name: Run python test
      shell: bash
      run: python3 clickhouse_test.py
        
