name: Checking stuff

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    
    runs-on: ubuntu-22.04

    steps:

    - name: swap off
      shell: bash
      run: |
        curl -sLS https://get.k3sup.dev | sh
        ls -l
        sudo install k3sup /usr/local/bin/
