name: ETL Pipeline

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_job:
    runs-on: ubuntu-22.04

    steps:
    
    - uses: actions/checkout@v4

    - name: Create docker network
      shell: bash
      run: docker network create --attachable --driver bridge analytics_network
    
    - name: Verify network
      shell: bash
      run: docker network ls
    
    - name: Create MySQL .env
      shell: bash
      working-directory: ./infra/mysql
      run: |
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
    
    - name: Setup MySQL
      shell: bash
      working-directory: ./infra/mysql
      run: docker compose up --build -d
    
    - name: Verify MySQL
      shell: bash
      run: docker ps && sleep 5 && docker ps
    
    - name: Test MySQL CLI in container
      shell: bash
      run: |
        MYSQL_USR=${{ secrets.MYSQL_USER }}
        docker exec -i -e MYSQL_PWD=${{ secrets.MYSQL_PASSWORD }} mysql_server mysql -h 127.0.0.1 -u$MYSQL_USR -e "SELECT 1;"

    - name: Create user tables
      shell: bash
      working-directory: ./infra/mysql
      run: |
        MYSQL_USR=${{ secrets.MYSQL_USER }}
        docker exec -i -e MYSQL_PWD=${{ secrets.MYSQL_PASSWORD }} mysql_server mysql -h 127.0.0.1 -u$MYSQL_USR < create_dim_fact.sql

    - name: Create .env
      working-directory: ./services/static-ecommerce
      shell: bash
      run: |
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
        echo "MYSQL_HOST=mysql_server" >> .env
        echo "MYSQL_PORT=3306" >> .env
    
    - name: Bulid ecommerce
      shell: bash
      working-directory: ./services/static-ecommerce
      run: |
        chmod +x ./build.sh && ./build.sh
    
    - name: Run ecommerce
      shell: bash
      working-directory: ./services/static-ecommerce
      run: |
        chmod +x ./run.sh && ./run.sh