name: ETL Pipeline

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_job:
    env:
      DATA_SOURCE_IMG: "ecommerce:latest"
      ETL_IMG: "etl:latest"
      NETWORK_NAME: analytics_network
      MYSQL_HOST: mysql_server
      MYSQL_PORT: 3306
      CLICKHOUSE_HOST: clickhouse_server
      CLICKHOUSE_PORT: 8123
    
    runs-on: ubuntu-22.04

    steps:
    
    - uses: actions/checkout@v4

    - name: Create docker network
      shell: bash
      run: docker network create --attachable --driver bridge $NETWORK_NAME
    
    - name: Verify network
      shell: bash
      run: |
        NET_DATA=$(docker network ls --filter "NAME=$NETWORK_NAME" --format json | jq)
        if [[ $NET_DATA == "" ]]; then 
          echo "Network not found"
          exit 1; 
        else 
          echo "$NET_DATA"
        fi
    
    - name: Create MySQL .env
      shell: bash
      working-directory: ./infra/mysql
      run: |
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
    
    - name: Setup MySQL
      shell: bash
      working-directory: ./infra/mysql
      run: docker compose up --build -d
    
#    - name: Test MySQL CLI in container
#      shell: bash
#      run: |
#        MYSQL_USR=${{ secrets.MYSQL_USER }}
#        docker exec -i -e MYSQL_PWD=${{ secrets.MYSQL_PASSWORD }} mysql_server mysql -h 127.0.0.1 -u$MYSQL_USR -e "SELECT 1;"
    - name: Create .env file for Clickhouse
      working-directory: ./infra/clickhouse
      shell: bash
      run: |
        echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> .env
        echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> .env

    - name: Clickhouse docker compose
      shell: bash
      working-directory: ./infra/clickhouse
      run: |
        docker compose up --build -d
    
    - name: Create .env for ecommerce
      working-directory: ./services/static-ecommerce
      shell: bash
      run: |
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
        echo "MYSQL_HOST=$MYSQL_HOST" >> .env
        echo "MYSQL_PORT=$MYSQL_PORT" >> .env
    
    - name: Create .env for ETL
      working-directory: ./services/etl
      shell: bash
      run: |
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
        echo "MYSQL_HOST=$MYSQL_HOST" >> .env
        echo "MYSQL_PORT=$MYSQL_PORT" >> .env
        echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> .env
        echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> .env
        echo "CLICKHOUSE_HOST=$CLICKHOUSE_HOST" >> .env
        echo "CLICKHOUSE_PORT=$CLICKHOUSE_PORT" >> .env
    
    - name: Bulid ecommerce
      shell: bash
      working-directory: ./services/static-ecommerce
      run: |
        docker build -t $DATA_SOURCE_IMG .
    
    - name: Bulid ETL
      shell: bash
      working-directory: ./services/etl
      run: |
        docker build -t $ETL_IMG .

    - name: Checking databases
      shell: bash
      run: |
        timeout 60s bash -c '
        until 
          source ./services/etl/.env;
          sudo docker exec -i -e MYSQL_PWD=$MYSQL_PWD $MYSQL_HOST mysql -u$MYSQL_USER -e"SELECT 1;" --silent; 
          do 
            echo "Waiting for MySQL"; 
            sleep 2; 
          done;
        '
        timeout 60s bash -c '
        until
          source ./services/etl/.env;
          curl -s \
            -H "X-ClickHouse-User: $CLICKHOUSE_USER" \
            -H "X-ClickHouse-Key: $CLICKHOUSE_PASSWORD" \
            --data "SELECT 1;" \
            "http://localhost:8123/" | grep -q "1"; 
            do
              echo "Waiting for ClickHouse";
              sleep 2;
            done;
        '

    - name: Run ecommerce
      shell: bash
      working-directory: ./services/static-ecommerce
      run: |
        docker run \
          --network $NETWORK_NAME \
          --env-file .env \
          $DATA_SOURCE_IMG --user 2 --product 3 --order 5
    
    - name: Run ETL
      shell: bash
      working-directory: ./services/etl
      run: |
        docker run \
          --network $NETWORK_NAME \
          --env-file .env \
          $ETL_IMG