name: Test for k8s

on:
  workflow_dispatch:

env:
  REDIS_HOST: redis-host-ts
  REDIS_PORT: 6379

jobs:

  provision_redis:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        tags: tag:ci
        retry: 3
        hostname: ${{ env.REDIS_HOST }}

    - name: Docker compose Redis
      shell: bash
      working-directory: ./infra/redis
      run: |
        docker compose up --build -d

    - name: Checking REDIS
      working-directory: ./utils/controller
      shell: bash
      run: |
        pip install -r requirements.txt
        timeout 60s bash -c '
        until 
          python3 main.py ping; 
          do 
            echo "Waiting for REDIS"; 
            sleep 2; 
          done;
        '
    
    - name: Submit and forget
      working-directory: ./utils/controller
      shell: bash
      run: |
        python3 main.py start --dep $REDIS_HOST --job main
        until 
          python3 main.py term --dep $REDIS_HOST
          do 
            echo "Waiting to finish $REDIS_HOST"; 
            sleep 2; 
          done;
  
  verify_redis:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        tags: tag:ci
        retry: 3
        hostname: redis-tester-ts
    
    - name: Checking Redis
      working-directory: ./utils/controller
      shell: bash
      run: |
        pip install -r requirements.txt
        timeout 60s bash -c '
        until 
          python3 main.py ping; 
          do 
            echo "Waiting for REDIS"; 
            sleep 2; 
          done;
        '

  provision_controllers:
    needs: verify_redis
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        component:
          - hostname: kube-controller-1
          - hostname: kube-controller-2
    steps:
      - uses: actions/checkout@v4

      - uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TS_AUTH_KEY }}
          tags: tag:ci
          retry: 3
          hostname: ${{ matrix.component.hostname }}

      - name: SSH up
        shell: bash
        run: sudo tailscale up --ssh --accept-routes --hostname=${{ matrix.component.hostname }}
      
      - name: Get hostname
        shell: bash
        run: hostname && hostname -I

      - name: Submit and forget
        working-directory: ./utils/controller
        shell: bash
        run: |
          pip install -r requirements.txt
          python3 main.py start --dep $REDIS_HOST --job controller
          until 
            python3 main.py term --dep $REDIS_HOST
            do 
              echo "Waiting to finish $REDIS_HOST"; 
              sleep 2; 
            done;
  
  ssh_on_vms:
    needs: verify_redis
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        component:
          - hostname: kube-controller-1
          - hostname: kube-controller-2
    
    steps:

      - uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TS_AUTH_KEY }}
          tags: tag:ci
          retry: 3
          hostname: ssh-tester-ts-${{ matrix.component.hostname }}
      
      - name: test ssh
        shell: bash
        run: |
          echo "TS_DNS=${{ secrets.TS_DNS }}" >> .env
          echo "SSH_HOST=${{ matrix.component.hostname }}" >> .env
          timeout 120s bash -c '
          until
            source .env
            RES=$(ssh -o StrictHostKeyChecking=no root@${SSH_HOST}.${TS_DNS} "hostname -I"); 
            do
            echo "SSH failed"
            sleep 2;
            done;
            echo $RES
          '
  clean-up:
    needs: ssh_on_vms
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TS_AUTH_KEY }}
          tags: tag:ci
          retry: 3
      
      - name: Terminate Infra
        working-directory: ./utils/controller
        shell: bash
        run: |
          pip install -r requirements.txt
          python3 main.py finish --dep $REDIS_HOST --job controller
          python3 main.py finish --dep $REDIS_HOST --job main