name: Sample Pipeline

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  data-pipeline:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Create docker network
      shell: bash
      run: docker network create --attachable --driver bridge analytics_network
    
    - name: Verify network
      shell: bash
      run: docker network ls
    
    - name: Create .env file for Clickhouse
      working-directory: ./infra/clickhouse
      shell: bash
      run: |
        echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> .env
        echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> .env

    - name: Verify .env
      working-directory: ./infra/clickhouse
      shell: bash
      run: ls -l .env

    - name: Clickhouse docker compose
      shell: bash
      working-directory: ./infra/clickhouse
      run: |
        docker compose up --build -d
    
    - name: Verify Clickhouse
      shell: bash
      run: |
        docker ps
    
    - name: Bulid banner data generator
      shell: bash
      working-directory: ./utils/banner-data
      run: |
        chmod +x ./build.sh && ./build.sh
    
    - name: Create .env file for Data Generator
      working-directory: ./utils/banner-data
      shell: bash
      run: |
        echo "CLICKHOUSE_HOST=clickhouse_server" >> .env
        echo "CLICKHOUSE_PORT=8123" >> .env
        echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> .env
        echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> .env

    - name: Run banner data generator
      shell: bash
      working-directory: ./utils/banner-data
      run: |
        chmod +x ./run.sh && ./run.sh
    
    - name: Bulid reporter
      shell: bash
      working-directory: ./services/reporter
      run: |
        chmod +x ./build.sh && ./build.sh
    
    - name: Create .env for reporter
      working-directory: ./services/reporter
      shell: bash
      run: |
        echo "CLICKHOUSE_HOST=clickhouse_server" >> .env
        echo "CLICKHOUSE_PORT=8123" >> .env
        echo "CLICKHOUSE_USER=${{ secrets.CLICKHOUSE_USER }}" >> .env
        echo "CLICKHOUSE_PASSWORD=${{ secrets.CLICKHOUSE_PASSWORD }}" >> .env
    
    - name: Run reporter
      shell: bash
      working-directory: ./services/reporter
      run: |
        chmod +x ./run.sh && ./run.sh