name: Test TailScale

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_tailscale:
    runs-on: ubuntu-22.04
    steps:
      - name: Test
        shell: bash
        run: echo 1
      - uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TS_AUTH_KEY }}
          tags: tag:ci
          retry: 2
          hostname: test-host
