name: Test MySQL Connection

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_job:
    runs-on: ubuntu-22.04

    steps:
    
    - uses: actions/checkout@v4

    - name: Create MySQL .env
      shell: bash
      working-directory: ./infra/mysql
      run: |
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
    
    - name: Setup MySQL
      shell: bash
      working-directory: ./infra/mysql
      run: docker compose -f docker-compose-dev.yaml up --build -d
    
    - name: Verify MySQL
      shell: bash
      run: docker ps

    - name: Create .env
      working-directory: ./tests/mysql_read_write
      shell: bash
      run: |
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
        echo "MYSQL_HOST=mysql_server" >> .env
        echo "MYSQL_PORT=3306" >> .env
    
    - name: Download python requirements
      shell: bash
      working-directory: ./tests/mysql_read_write
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run python test
      shell: bash
      working-directory: ./tests/mysql_read_write
      run: python3 main.py